# Generated by Django 4.2.6 on 2023-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='Marca',
            field=models.CharField(default='Toyota', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autos',
            name='Modelo',
            field=models.CharField(default='Yaris', max_length=100),
            preserve_default=False,
        ),
    ]
