# Generated by Django 3.2.8 on 2023-10-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_autos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
