# Generated by Django 3.2.8 on 2023-10-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20231023_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
    ]
