# Generated by Django 3.2.8 on 2023-10-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_autos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='Imagen2',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
