# Generated by Django 3.2.8 on 2023-10-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_autos_imagen2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autos',
            name='Imagen2',
        ),
    ]
