# Generated by Django 3.2.8 on 2023-10-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_usuario_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Autos',
        ),
    ]
