# Generated by Django 3.2.8 on 2023-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_autos_imagen2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='autos',
            name='Marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='autos',
            name='Modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
    ]
